# Generated by Django 5.2.4 on 2025-07-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSwitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('current_background', models.CharField(max_length=150)),
                ('target_role', models.CharField(max_length=150)),
                ('motivation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=150)),
                ('current_role', models.CharField(max_length=150)),
                ('linkedin', models.URLField(blank=True)),
                ('bio', models.TextField()),
                ('offers_mentoring', models.BooleanField(default=False)),
            ],
        ),
    ]
