# Generated by Django 5.2.4 on 2025-07-19 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('location', models.TextField(help_text='Available area / Pincode')),
                ('skills', models.JSONField(help_text="Example: ['nurse', 'childcare', 'cook']")),
                ('experience_years', models.PositiveIntegerField()),
                ('languages', models.JSONField(help_text="Example: ['Hindi', 'Telugu']")),
                ('documents', models.JSONField(help_text="e.g. {'aadhar': 'url', 'certificate': 'url'}")),
                ('rating', models.FloatField(default=0.0)),
                ('availability', models.JSONField(help_text="e.g. {'mon': ['9am-1pm'], 'tue': ['full_day']}")),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.TextField()),
                ('location', models.TextField(help_text='City / Area / Pincode')),
            ],
        ),
    ]
